### ISSUE TITLE
Conditional compilation issues

### ISSUE THREAD

**Issue by Alekcvp** [the-Arioch/uib#3]
There are issues with conditional defines in source files, leading to the strange things after the compilation:

For ex: 
uiblib.pas(128): {$IFDEF **FB21_UP**}
uiblib.pas(144): {$IFNDEF **FB_21UP**}

**Comment by the-Arioch** [comment]
what exactly "unusable" mean ?

what is FB version and testcase ?

**Comment by Alekcvp** [comment]
Answered in #2.

**Comment by the-Arioch** [comment]
Line 128 is about charsets, not transactions.

Perhaps FB 2.1 added special requirements about  those options, that woked in FB 2.0 and before

      isc_tpb_shared,
      isc_tpb_protected,
      isc_tpb_exclusive,

**Comment by Alekcvp** [comment]
> Line 128 is about charsets, not transactions.

I mean: compare the defines! FB**21**_UP & FB_21UP. 2nd variable is never defined anywhere and is just a typo. And this is not the full list of wrong directives.

**Comment by the-Arioch** [comment]
Line 128 was modified 2008-11-07 11:43 as a15fc978ba1e9f0f5aa49c93d31cb4fabec55599 with comments "unicode dataset" and "Delphi 2009"

should not be an issue

**Comment by the-Arioch** [comment]
ah, perhaps a typo indeed, thanks for spotting

**Comment by the-Arioch** [comment]
Line 144 is changed as 7d029679afe064414a9f2a3a2934afd9d2208419 
on 2010-02-15 13:00
with comment "fix lockimeout"

i wonder...

**Comment by Alekcvp** [comment]
same fix, again:
```
+    {$IFNDEF **FB_21UP**}
 +      isc_tpb_shared,
 +      isc_tpb_protected,
 +      isc_tpb_exclusive,
 +    {$ENDIF}
```

**Comment by the-Arioch** [comment]
C:\Delphi\Libs\uib_git\source\uibase.pas [1]
  C:\Delphi\Libs\uib_git\source\uibase.pas(1551): {$IFNDEF FB_21UP}
C:\Delphi\Libs\uib_git\source\uiblib.pas [2]
  C:\Delphi\Libs\uib_git\source\uiblib.pas(144):   {$IFNDEF FB_21UP}
  C:\Delphi\Libs\uib_git\source\uiblib.pas(1779):     {$IFNDEF FB_21UP}

Quick fix would be to fix those names, but then those options would be no more available if you compie against FB newer than 2.0

i would have to check into changes and API, to see if i can re-enable them without some weird side-effects

this topic is completely new to me

**Comment by Alekcvp** [comment]
> but then those options would be no more available if you compie against FB newer than 2.0

They do not work with it anyway (in the current way).

**Comment by the-Arioch** [comment]
to read

theory: http://www.sql.ru/forum/actualutils.aspx?action=gotomsg&tid=451811&msg=4391275
2.1 practice: http://firebird.1100200.n4.nabble.com/2-1-td1283997.html

**Comment by Alekcvp** [comment]
Оттуда:
> Там выходит что блокировки на таблицы ставятся в самый конец, уже после флагов
isc_tpb_nowait/isc_tpb_wait и isc_tpb_ignore_limbo, isc_tpb_autocommit, isc_tpb_no_auto_undo. _А надо объявлять isc_tpb_lock_write и isc_tpb_protected до этих флагов ну и до wait/nowait_

**Comment by the-Arioch** [comment]
Это обрывки, Когда будет время надо полноценно API Guide прочитать будет на эту тему
